### ISSUE TITLE
Get trending projects from API

### ISSUE THREAD

**Issue by redstone-scratch** [redstone-scratch/Snazzle#1]

**Comment by EngineerRunner** [comment]
the api to get trending projects is
api.scratch.mit.edu/explore/projects?limit={limit}&offset={offset}&language={language}&mode=trending&q=*

**Comment by redstone-scratch** [comment]
> the api to get trending projects is api.scratch.mit.edu/explore/projects?limit={limit}&offset={offset}&language={language}&mode=trending&q=*

Oh thanks

**Comment by redstone-scratch** [comment]
Reopened as I have not added this yet

**Comment by redstone-scratch** [comment]
The endpoint doesn't work

**Comment by ajskateboarder** [comment]
this has been fixed
