### ISSUE TITLE
Fonts not working from local

### ISSUE THREAD

**Issue by redstone-scratch** [redstone-scratch/Snazzle#34]
Strangely, the local fonts don't load on my machine. They just go to the default, like `sans-serif` or `monospace`.

**Comment by Darth-Ness** [comment]
Playing around in the network tab, it seems like some of the fonts are returning 404, and 403. I'll look and see what's wrong.

**Comment by Darth-Ness** [comment]
Update: Part of the problem was I kept spelling '.ttf' as '.tff' causing the 404's
I'm going to look into the other issues.

**Comment by Darth-Ness** [comment]
Found the issue. PR coming soon.
