### ISSUE TITLE
Migrate to SQLite

### ISSUE THREAD

**Issue by ajskateboarder** [redstone-scratch/Snazzle#39]
It's much more appropriate for what we're doing: saving usernames and auth tokens

**Comment by redstone-scratch** [comment]
Yeah maybe lol

**Comment by redstone-scratch** [comment]
> I'll make a PR
> 
> I've been having quite a bit of issues getting a supabase instance up locally

No, no, no, don't locally make a supabase instance! Instead create a project on their site and do it that way...
